{{- if not .Values.connections.existingConnectionsSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commentarr.connectionsSecretName" . }}
  labels:
    {{- include "commentarr.labels" . | nindent 4 }}
type: Opaque
stringData:
  plex-token: {{ .Values.connections.plex.token | default "" | quote }}
  jellyfin-api-key: {{ .Values.connections.jellyfin.apiKey | default "" | quote }}
  prowlarr-api-key: {{ .Values.connections.prowlarr.apiKey | default "" | quote }}
  download-client-username: {{ .Values.connections.downloadClient.username | default "" | quote }}
  download-client-password: {{ .Values.connections.downloadClient.password | default "" | quote }}
{{- end }}
